### ISSUE TITLE
mendex.1 の日本語版 pLaTeX 化と英語版の作成

### ISSUE THREAD

**Issue by aminophen** [texjporg/mendex-doc#1]
mendex の man ドキュメントが文字化けしている ([forum:2057](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2057)) に関して、2016/11/08 現在の mendex 周りの状況を整理しておきます。

- mendex のバイナリは Package ptex.ARCH (ARCH はプラットフォーム) に含まれている
- mendex のドキュメント (mendex.1, mendex.man1.pdf) は Package ptex に含まれている
- `man mendex` は mendex.1 を表示するが、日本語が Mac では文字化けする
- `texdoc mendex` は mendex.man1.pdf を表示する

本リポジトリで Debian 由来の mendex.1（英語版）の 2.6e → 2.6f へのアップデート、および mendex.1.ja（TeX Live の現在の mendex.1）の pLaTeX 文書化を行います。

ちなみに upmendex のバイナリは Package ptex.ARCH に含まれていて、upmendex のドキュメント (README.md, upmendex.doc) は Package uptex に含まれています。`texdoc upmendex` は README.md をターミナル上にテキスト表示しますが、英語で書かれていて問題なさそうです。

**Comment by kmaed** [comment]
単に名前の問題ですが，mendex のドキュメントだけならばレポジトリ名は mendexdoc か mendex-doc の方が良いのではないかと思いました．

書くところがここじゃないような気がしつつ……．

**Comment by aminophen** [comment]
mendex-doc にリネームしました。先ほどまでの mendex の URL からは（GitHub の機能で勝手に）リダイレクトされるようになっています。

**Comment by wtsnjp** [comment]
mendex 日本語ドキュメント（pLaTeX 文書）の作成作業に着手しています．

書式だけ変更してもいいのですが，man から pLaTeX 文書に切り替えたことにより「ツール」を「コマンドラインツール」とした方が明確になるなど工夫の余地がありそうなので若干の改変を行いたいのですが，大丈夫でしょうか？

また `\author` への記述は「日本語 TeX 開発コミュニティ」としても構わないでしょうか？

**Comment by aminophen** [comment]
ワトソンさん

「工夫の余地」については、もちろんライセンスの許す範囲ですので、私は改変してよいと思います。たたき台として mendex.1.ja →(mandoc)→ mendex.html →(html2latex)→ mendex.tex と機械変換したものをリポジトリに置きましたが、情報が不足しなければこれを基にしなくてもよいです。

\author はアスキーが LICENSE に明記された Copyright に入っているはずですから、アスキー・メディアワークスとの並列にしておけば無難でしょう。

**Comment by aminophen** [comment]
ひととおり作業が落ち着いたということで、CTAN と TeX Live への反映に移りましょう。みなさまありがとうございます。

- mendex.1, mendex.1.ja, mendex.doc → GitHub:texjporg/tex-jp-build にコミット（→ TeX Live trunk/Build へと sync していただく）
- mendex.tex, mendex.pdf, README.md, LICENSE → CTAN:info/mendex-doc にアップロード（→ ctan2tds で TeX Live へ収録）

という流れで進めてよろしいでしょうか。

**Comment by aminophen** [comment]
CTAN には昼にアップロードしました。

- https://www.ctan.org/tex-archive/info/mendex-doc

に反映されるようです。

**Comment by aminophen** [comment]
[r42752](http://tug.org/svn/texlive?view=revision&revision=42752) で TeX Live に反映されたようですが

- texmf-dist/doc/latex/mendex-doc

に入っているようです。これでいいのかな？

**Comment by aminophen** [comment]
TeX Live でのパスが [r42767](http://www.tug.org/svn/texlive?view=revision&revision=42767) で texmf-dist/doc/support/mendex-doc に変わりました。英語版 mendex.1（ただし「読み」の具体例の説明には日本語文字を含む）は [r42761](http://www.tug.org/svn/texlive?view=revision&revision=42761) で mendex のソースディレクトリに入れていただき、新しい mendex.man1.pdf もコミットしていただきました。

というわけで完了です。みなさまありがとうございました。
