### ISSUE TITLE
並べ替え順序のドキュメント

### ISSUE THREAD

**Issue by aminophen** [texjporg/mendex-doc#10]
https://github.com/texjporg/tex-jp-build/issues/116 の関連でドキュメントを読んでいて気づきました。

mendex のソースコード (var.h) を見ると `character_order` の初期値は SEJ ではなく SNEJ のようです。さらに sort.c を見てもやはり N が認識されます。ところが，mendex のドキュメントには

> makeindex には索引項目の分類として「記号」，「アルファベット」の他に，数字のみの項目として「数字」という分類がありますが，mendex では数字は「記号」に含まれます．

とあります。分類は一緒なのに，並べ替えは数字と記号を別にできる？？？ 挙動を確認できていませんが，一貫していないような気がします。

**Comment by aminophen** [comment]
mendex の挙動を確認したところ，mendex の `character_order` には S, N, E, J が認識できるようで，既定値は SNEJ でした。また，S と N をくっつけた状態での順序入れ替えは正常に機能しました（例：NSEJ, EJSN など）。ところが，S と N を離した場合がよくわかりません。

確かに索引エントリは2個のブロックに分離しますが：

* `lethead_flag 1` の場合 → `symhead_positive` の文字列が1個目のブロックだけに出る（2個目は空）
* `lethead_flag -1` の場合 → `symhead_negative` の文字列が1個目のブロックだけに出る（2個目は空）
* `lethead_flag` がゼロでなく `symbol` が定義されている場合 → `symbol` の文字列が1個目と2個目のブロックに2回出る

以上の挙動から「S と N を離れて指定するのは想定外」だと思います（注意：今のドキュメントを真似て "SEJ" と書くと "N" が漏れて最後の扱いとなる＝実質的に "SEJN" すなわち「S と N を離れて指定した」状態と等価になってしまう）。

* N が言及されていないのはドキュメントのバグであり，既定値は "SNEJ" が正しい。
* さらに S と N は必ず隣り合わせてくださいと明記する。

としようと思います。（もし問題があればおしらせください > @t-tk 様）

**Comment by t-tk** [comment]
mendex の `character_order` を私が触った記憶はなく、おそらく、挙動はASCIIさんのオリジナルの頃から変わっていないと思います。
ドキュメントと実際の挙動が食い違っているとすると、ドキュメントかあるいは動作のバグと認識してよいと思います。
今回の件は、実際の挙動にドキュメントを合わせる方向でよいと思います。

* N が言及されていないのはドキュメントのバグであり，既定値は "SNEJ" が正しい。

これは賛成です。

* さらに S と N は必ず隣り合わせてくださいと明記する。

これも、現状追認という意味で賛成です。
ただし、ひょっとして挙動の方を自由な順序でも動くように直すことは出来ないものか、という風にも思います。
どのくらい大変なのか、修正可能なのか気になります。

upmendex を作ったとき  `character_order`もmendexをベースに多言語に拡張したはずですが、詳細は覚えていません。
upmendex でも同じ問題を抱えたままになっているかもしれません。

**Comment by t-tk** [comment]
余談ですが、まだまだバグが時々見つかるところをみると、オプションを総なめするような網羅的なテストが行われていないようで、ドキュメントと実際の挙動が食い違うケースは他にもまだ残っているような気がしています。
`character_order` は mendex オリジナルのパラメータなので該当しませんが、makeindex 互換を意図していたもののそうなっていないケースもまだ残っているような気がします。

**Comment by aminophen** [comment]
> ひょっとして挙動の方を自由な順序でも動くように直すことは出来ないものか

不可能ではないと思いますが，アスキーさんの「数字と記号は一緒の分類に含めるのが mendex の仕様である」という意図に反する気がするので，あまり頑張らなくても良いかなと思っています。

> makeindex に存在するスタイルパラメータのうち，  |numhead_positive|と|numhead_negative|は認識されません．

わざわざこの記述があることからすると，数字だけという分類は廃止したかったように感じました。

**Comment by aminophen** [comment]
> * N が言及されていないのはドキュメントのバグであり，既定値は "SNEJ" が正しい。
> * さらに S と N は必ず隣り合わせてくださいと明記する。

af410b9 でドキュメントに反映しました。

また，非常に細かい点ですがドキュメント `-g` オプションの説明に

> 指定しないと「あいうえ……わをん」になります

とあるのに対し，実際の挙動は「ゐゑ」が索引項目にある場合は見出しになりうる（全48文字）ので，括弧書きで記載しました (4896431)。テスト用の入力ファイル [allkana-jisx0208.idx](https://gist.github.com/aminophen/8e49984c6f5aad2a45061ecab34d9210) を使って確認しています。

**Comment by t-tk** [comment]
> 実際の挙動は「ゐゑ」が索引項目にある場合は見出しになりうる（全48文字）ので，括弧書きで記載しました

オリジナルの記述を尊重する意味でこういう形になさったのかもしれませんが、注釈ではなくて単純に

> 指定しないと「あいうえ……わゐゑをん」になります

でよいような気が私はします。

**Comment by aminophen** [comment]
そうですね，注釈ではなく単純にしておきました。

**Comment by aminophen** [comment]
ドキュメントについてさらに詳しく調べて気づいたことがあります。

(1) makeindex は `lethead_...` のキーを認識しません（すなわち現在は mendex 独自になっています）。昔の makeindex の実装がどうだったのかはわかりませんが，makeindex のドキュメント ind.pdf を見ると

> the `lethead_*` directives are now `|heading_*|`

と書かれているため，途中で makeindex の仕様変更があったのかもしれません。

(2) makeindex には `headings_flag` がありますが `heading_flag` はありません。一方 mendex には `heading_flag` が `lethead_flag` のエイリアスとして実装されています。makeindex 用のスタイルを mendex に流用した場合，mendex は `headings_flag` を認識しないため非互換が生じます。

両方とも，実装にドキュメントを合わせ込む方向で「makeindex との違い」に書くことにしようと思います（新たに `headings_flag` も mendex に認識させるのも簡単ですが…）。

**Comment by t-tk** [comment]
アスキー社さんのオリジナルの mendexk2.6f.tar.gz の中の ChangeLog に以下の記述を見つけました。
mendex 2.5 は [17-Jan-2002] だそうです。
makeindex の方は TeX Live svn に残っている最古のものは 2006年のようです。 https://www.tug.org/svn/texlive/trunk/Build/source/texk/makeindexk/scanst.h?view=log
これから先は想像の域を出ませんが、以下のどちらかかも知れません。

1. makeindex の仕様はほとんど凍結されていて現在のmakeindexとほぼ同じだが、アスキー社さんがmendexに取り込んだ際に互換にするつもりが `hedings_flag` → `heading_flag` の取り違えが起こった
2. 2002年頃の makeindex には `heading_flag` が存在したが、アスキー社さんがmendex に取り込んだ後に makeindex では `headings_flag` に変更された。


```
2.4f->2.5
・-s オプション使用時にスタイルパラメータ escape の値がおかしくなっていたので
  修正。
・makeindexに合わせるため、以下ように仕様を変更。
  1. -c オプション時の動作を修正。makeindex では索引語の前後の空きを削除するが、
     mendex では空きが残っていたので、削除するようにした。
  2. makeindex で使用されているスタイルパラメータのうち、mendexでサポートされて
     いなかったものを追加サポート。
       delim_t
       suffix_2p
       suffix_3p
       suffix_mp
       heading_flag
       heading_prefix
       symhead_positive
       symhead_negative
     ただし、以下の makeindex 用パラメータは無視される。
       numhead_positive
       numhead_negative
(後略)
```

古すぎて歴史的事情を探るのも限界がありそうです。実装に合わせて記述するのに賛成です。

**Comment by t-tk** [comment]
CTAN にある [makeindex 2.12](https://www.ctan.org/pkg/makeindex) のソースは1989年頃のもののようですね。その時既に `headings_flag` だったようです。従って私の推測はこちらになりました。

1. makeindex の仕様はほとんど凍結されていて現在のmakeindexとほぼ同じだが、アスキー社さんがmendexに取り込んだ際に互換にするつもりが hedings_flag → heading_flag の取り違えが起こった

**Comment by aminophen** [comment]
> 実装に合わせて記述する

7a060c2 で完了しました。

**Comment by aminophen** [comment]
[上のコメント](https://github.com/texjporg/mendex-doc/issues/10#issuecomment-850987326)で書いた

> `lethead_flag 1` の場合 → `symhead_positive` の文字列が1個目のブロックだけに出る（2個目は空）
> `lethead_flag -1` の場合 → `symhead_negative` の文字列が1個目のブロックだけに出る（2個目は空）

この「2個目が空」なのは mendex 2.4f → 2.5 の時に `symhead_positive` と `symhead_negative` を新たにサポートした時の考慮漏れのような気がしてきました。元々 mendex にあった `symbol` のコードが2か所あるのに，追加サポート時に片方しか見なかったのだと推測します。tex-jp-build の方に書きます。 → https://github.com/texjporg/tex-jp-build/issues/117

**Comment by aminophen** [comment]
> makeindex と mendex の互換性

吉永徹美 著『LaTeX2e辞典 増補改訂版』(2018) の気になる記述を。付録F章のタイトルは「mendex」ですが，mendex をベースにしつつ makeindex との違いについても逐一言及されています。

(1) p.512

> 文字型の値として文字「'」を指定する場合，mendex 用の ist ファイルでは「\'\'\'」と記述しますが，makeindex 用の ist ファイルでは「\'\\\'\'」と記述します．

(2) p.516 

> makeindex を用いる場合には，`page_precedence` パラメータでの「r」などの順序を文書全体における「ページ番号の形式の変更順」に合わせておくと，（idx ファイルを複数に分割している場合にも）索引項目でのページ番号リストを適切に並べ替えることができます．

わざわざ「makeindex を用いる場合には」という表現をしているところが，裏を返せば「mendex では一部うまくいかない」ということをほのめかしているのでしょうか。これは https://github.com/texjporg/tex-jp-build/issues/112 と関係しますが，まだ調べられていません。

**Comment by aminophen** [comment]
(3) p.516 に `character_order` と `priority` の注意点も書かれていました。この記述は確かに実際の挙動を表していましたので，早速 39d384b でドキュメントに反映しました。

> なお，|character_order| に関係する文字種の判別においては，
> 半角スペースも「記号」として扱われます．
> この仕様により，|priority| の値はデフォルト|0|のままで，
> |character_order| を |"JESN"| とした場合にも
> 日本語−英字間のソート順序は |priority| を|1|にした時と同様になります．

標準として作成した jpbase.ist には，今のところ私が勝手に `character_order "JESN"` を設定してしまいましたが，このドキュメント通りに `priority` が意味を持たなくなってしまうようです。（0としても1としても変化しない）

**Comment by aminophen** [comment]
> `character_order`

LaTeX の参考書の索引を見てもあまり参考にならないので，より実用的な手許にあった化学系の本（出版社：東京化学同人，化学同人，丸善，朝倉書店，講談社）をランダムに20冊ほど取って索引を見てみました。ざっと「欧文→和文」の順が6割，「和文→欧文」の本が1割，残りが「欧文索引と和文索引を分ける」あるいは「欧文はよみがなを振って和文の索引に含める」という感じでした。というわけで jpbase.ist では `character_order` を変更せずデフォルトに任せます。

**Comment by t-tk** [comment]
>  吉永徹美 著『LaTeX2e辞典 増補改訂版』(2018)

私はこの本を持っていなくて確認できないのですが、商業出版物の記述の表現をそのまま転記するのは著作権上気になります。
引用と分かる形(%のコメントではなく)で記載した上で参考文献を明示するか、表現は改めたほうがよいと思います。

**Comment by aminophen** [comment]
本の表現そのまま引用してはいませんのでご安心ください。％で記載したのは，これを参考文献としてあげるというよりは，「意見は割れるかもしれないがまあまあ知られた挙動であり不具合とはみなされない」という開発者向けメモのような意図で載せていました。でも挙動調査のきっかけとして参考にしたのは確かなので，末尾に書籍名を載せておくようにしましょうかね。

**Comment by t-tk** [comment]
表現がそのままでないとのこと、了解しました。

> 末尾に書籍名を載せておく

先人の吉永さんの貢献を明らかにできてよいことだと思います。

**Comment by aminophen** [comment]
参考文献に (1) 吉永さんの本と，jpbase.ist の設計で参考にした (2) munepi さんの Qiita 記事，それに (3) 熊澤さんのサイト を載せておきました。ほぼ仕様が固まってきましたので master にマージしました。スタイルの例は jpbase.ist 一個ですが，mendex.pdf にその説明を付けましたので，十分だと考えます。
