### ISSUE TITLE
symbol_flag=2, character_orderで記号と数字のグループ分離

### ISSUE THREAD

**Issue by t-tk** [texjporg/mendex-doc#12]
https://github.com/texjporg/tex-jp-build/issues/124 に関連して、mendex v3.6 [6-Jun-2021]で`symbol_flag=2` を設定した場合にcharacter_orderで記号と数字のグループを区別するようにしました。character_orderでS,Nを離して配置できるようにしました。

roffフォーマットマニュアルには反映させたつもりですが mendex.tex はまだ更新していません。

**Comment by aminophen** [comment]
https://github.com/texjporg/mendex-doc/commit/d32235c3dde71aa45ccee1ddc6381185e867d051 で mendex.tex を更新いただいていたのを確認しました。ありがとうございます。TeX Live 2021 が frozen になった後で CTAN に投稿しようと思います。

**Comment by aminophen** [comment]
2022-04-05 CTAN 投稿済み。
