### ISSUE TITLE
ファイル構成の整理, サポート先など

### ISSUE THREAD

**Issue by t-tk** [texjporg/mendex-doc#8]
ファイルの構成について整理したいと思います。
現状は以下の通りです。

* mendex.1 (roff): English man page (-> source of mendex.man1.pdf)
* mendex.1.ja (roff): Japanese man page
* mendex.tex: pLaTeX source of Japanese man page (-> mendex.pdf)
* mendex.doc: plain text version of mendex.1.ja
* README_asciimw: historic purpose only (by ASCII MEDIA WORKS) 

mendex.1 は、元のmendex.1(日本語) を英語に翻訳したもので、mendex.man1.pdf のソースになっている他 man によるコマンドライン上のマニュアルのソースになっています。
mendex.1.ja は、元のmendex.1(日本語) をリネームしたもので、やや編集が滞りがちでした。しかし、man によるコマンドライン上のマニュアルの日本語版として利用価値があると思います。
mendex.tex は、日本語マニュアルのpdf版ソースになっており、現状一番よくメンテナンスされています。
mendex.doc は、元はmendex.1(日本語) をテキストファイル化したものでした。若干編集が滞りがちのようです。
README_asciimw はアスキー社さんによるオリジナルのREADMEです。コンパイル方法など現状とあわない旧い情報も含まれますが、<特徴>, <kpathsea の環境変数について> などmendex.1.ja 等には盛り込まれていない情報も含まれています。

私の意見は以下です。

* mendex.1.ja は、man によるコマンドライン上のマニュアルの日本語版向けにメンテナンスを継続する。
* mendex.doc は、mendex.1.ja, mendex.tex, mendex.pdf と重複するので削除する。あるいは、groff で自動生成できるものに差し替え mendex.ja.txt のようなファイル名に変更する。
* README_asciimw は、今の段階では残す。将来、全ての情報が mendex.1.ja に含まれた場合には削除しても良い。
* mendex のサポート先を「日本語TeX開発コミュニティ issue@texjp.org」とする。英語版 README を作成し、サポート先として明記する。

mendexのメンテナーは成り行き上私になっていましたが、そろそろコミュニティーに移させてもらういい頃合いじゃないかな、と思います。もちろん、私が手をいれた部分に問題が生じた場合には、私が最大限対応するつもりです。
READMEについては、別案として、冒頭部分を英語のREADMEにして、後ろの方に README_asciimw の内容を引用する形でもよいです。

**Comment by t-tk** [comment]
若干意見を修正します。

* README_asciimw, ChangeLog* は、現状も mendex-doc のCTANアーカイブに含まれていないので、
今後もmendex-doc には含めない。mendex-docリポジトリから削除し、Build/source/texk/mendexk の方に残す。

今回書いた README_mendex.md は、CTAN の mendex-docリポジトリに含めても良いし、Build/source/texk/mendexk に入れるだけでも良いです。

**Comment by norbusan** [comment]
ユーザ向けのドキュメントをCTANにアップした方がいいと思います。Build/sourceに入ってるファイルを結局誰も読んでいない気がします。

他のこと：

- `README_mendex.md` と`README.md`の両方が要らないと思います
- `README_mendex.md`はまだ`README_asciimw`を述べています

この２つの点を直せばマージしていいと思います。

**Comment by t-tk** [comment]
@norbusan さん、コメントありがとうございます。

> - `README_mendex.md` と`README.md`の両方が要らないと思います

「両方とも要らない」ということでしょうか? 「片方は要らない」「2個は要らない」ということでしょうか?
少なくともCTAN向けに mendex-doc の README.md は必要なので、内容的にマージすることを試してみます。

CTANへのリリース時期は #7 ではTeX Live 2019フリーズの直前という合意になっていました。
#8 も大きな変更ではないので、そこまで待っても良いと思います。

**Comment by t-tk** [comment]
`README_mendex.md` に書いたことを `README.md` に取り込んでみました。
`README.md` は「`mendex-doc` の CTAN用 README」であるとともに source の方にもコピーして置こうと思っています。

**Comment by aminophen** [comment]
> README.md は…(略) source の方にもコピーして置こうと思っています。

コピー (duplicate) でなくとも，source の方にはもっと簡潔な

----
> The program mendex is a general purpose hierarchical index generator. It is almost compatible with makeindex, and additional features for Japanese (handling readings of kanji words etc.) are also available.
> See https://github.com/texjporg/mendex-doc for detail.
----

という感じの README でも十分ではないでしょうか？

**Comment by norbusan** [comment]
田中さん、変な日本語をすみません。はい、仰るとおり、１つだけ結構だと思います。
今の状況を確認しました。僕ならば、これでいいです。ありがとうございます。

**Comment by t-tk** [comment]
コメントありがとうございます。

> source の方にはもっと簡潔な (...) という感じの README でも十分ではないでしょうか？

好みの差なのだとは思いますが、以下の理由でその案は魅力的とは感じません。

* 「mendex-docを見よ」では、source ディレクトリを見ている人にとって、情報が削られた分参照先を見る手間を増やすことになる。
* mendex-doc の役割は、ユーザーマニュアルの整備、配布にある。source の方には、(未来の)開発者に知らせたい情報は集めておきたい。
* source ディレクトリは、mendex.1, mendex.1.ja を含む今の形を維持したい。README.mdとともに mendex-docと source ディレクトリをsyncする形にすればよい。それは大した手間ではない。

**Comment by aminophen** [comment]
いろいろありがとうございます。今確認したところで，これでいいと思います。

**Comment by t-tk** [comment]
ご協力ありがとうございました。
Build/source/texk/mendexk の方も以下の更新しました(r48247)。ここを閉じます。
mendex.1, mendex.1.ja (更新)
README.md (追加)
